/**
 * Seed data for venues from ai-context/venues-to-add.md
 * Matches the args of api.venues.create (without orderNum).
 */
export const seedVenues = [
  {
    name: "ARTECHOUSE",
    url: "https://www.artechouse.com/",
    submissionFormUrl: "https://artechouse.submittable.com/submit",
    locations: [
      { city: "Washington", state: "DC", country: "USA" },
      { city: "New York", state: "NY", country: "USA" },
      { city: "Houston", state: "TX", country: "USA" },
      { city: "Miami", state: "FL", country: "USA" },
    ],
    contacts: [
      { name: "Sandro Kereselidze", title: "Co-Founder & Chief Creative Officer", email: undefined, notes: undefined },
      { name: "Tati Pastukhova", title: "Founder & Managing Director", email: undefined, notes: undefined },
      { name: undefined, title: undefined, email: "press@artechouse.com", notes: "Best Contact (reaches founders' team)" },
    ],
    status: "Contacted" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Dedicated to immersive new media art experiences. Strategy: Mention collaborative installation + Holly's track record. Submission form: currently no open calls.",
  },
  {
    name: "Meow Wolf",
    url: "https://meowwolf.com/",
    submissionFormUrl: undefined,
    locations: [
      { city: "Santa Fe", state: "NM", country: "USA" },
      { city: "Las Vegas", state: "NV", country: "USA" },
      { city: "Denver", state: "CO", country: "USA" },
      { city: "Grapevine", state: "TX", country: "USA" },
      { city: "Houston", state: "TX", country: "USA" },
    ],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Large-scale interactive immersive installations.",
  },
  {
    name: "Art Club",
    url: "https://www.artclubhtx.com/",
    submissionFormUrl: undefined,
    locations: [{ city: "Houston", state: "TX", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: 'New Media Art Museum - "They draw with lasers, paint with video"',
  },
  {
    name: "Museum of Contemporary Digital Art (MoCDA)",
    url: "https://www.mocda.org/",
    submissionFormUrl: undefined,
    locations: [{ city: undefined, state: undefined, country: undefined, phoneNumber: undefined }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Dedicated digital art education and exhibitions. Location varies.",
  },
  {
    name: "Smithsonian American Art Museum",
    url: "https://americanart.si.edu/",
    submissionFormUrl: undefined,
    locations: [{ city: "Washington", state: "DC", country: "USA" }],
    contacts: [
      { name: "Saisha Grayson", title: "Curator (Time-Based Media)", email: undefined, notes: "PERFECT MATCH" },
      { name: undefined, title: undefined, email: "AmericanArtPressOffice@si.edu", notes: "Request forwarding to Saisha" },
      { name: undefined, title: undefined, email: undefined, notes: "Mailing: SAAM MRC 970 Box 37012, Washington, DC 20013-7012" },
    ],
    status: "Contacted" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Has specialized Time-Based Media collection & immersive gallery. Strategy: Specifically request time-based media curator review.",
  },
  {
    name: "MASS MoCA",
    url: "https://massmoca.org/",
    submissionFormUrl: "https://massmocastudios.submittable.com/submit",
    locations: [{ city: "North Adams", state: "MA", country: "USA" }],
    contacts: [
      { name: "Kristy Edmunds", title: "Director (since 2021)", email: undefined, notes: undefined },
      { name: undefined, title: undefined, email: undefined, notes: "Contact: 413.662.2111 or general contact form on massmoca.org" },
      { name: undefined, title: undefined, email: undefined, notes: "Mailing: 1040 MASS MoCA Way, North Adams, MA 01247" },
    ],
    status: "Contacted" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "One of world's largest contemporary art museums, embraces all media. Strategy: Reference large-scale contemporary installation capability.",
  },
  {
    name: "Phoenix Art Museum",
    url: "https://phxart.org/",
    submissionFormUrl: undefined,
    locations: [{ city: "Phoenix", state: "AZ", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Strong Contemporary Collection with video, digital and new media.",
  },
  {
    name: "Museum of Contemporary Art Chicago",
    url: "https://mcachicago.org/",
    submissionFormUrl: undefined,
    locations: [{ city: "Chicago", state: "IL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Champions new and unexpected contemporary art.",
  },
  {
    name: "Whitney Museum of American Art",
    url: "https://whitney.org/",
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Has dedicated artport gallery for Internet and new-media art.",
  },
  {
    name: "New Museum",
    url: "https://www.newmuseum.org/",
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Major contemporary venue, strong digital art program.",
  },
  {
    name: "ZKM Center for Art and Media",
    url: "https://zkm.de/en",
    submissionFormUrl: undefined,
    locations: [{ city: "Karlsruhe", state: undefined, country: "Germany" }],
    contacts: [
      { name: "Philipp Ziegler", title: "Curatorial Contact", email: undefined, notes: undefined },
      { name: undefined, title: undefined, email: "curators@zkm.de", notes: "Direct Email" },
      { name: undefined, title: undefined, email: undefined, notes: "Phone: +49 (0) 721/8100-1303" },
    ],
    status: "Contacted" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "GOLD STANDARD - Worldwide unique institution for media art. Strategy: Emphasize innovative tech + art collaboration.",
  },
  {
    name: "Ars Electronica Center",
    url: "https://ars.electronica.art/center/en/",
    submissionFormUrl: undefined,
    locations: [{ city: "Linz", state: undefined, country: "Austria" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Leading digital art venue with Museum of the Future.",
  },
  {
    name: "teamLab Borderless/Planets",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Tokyo", state: undefined, country: "Japan" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "World's most visited single-artist museum for immersive art.",
  },
  {
    name: "ArtScience Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Singapore", state: undefined, country: "Singapore" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Features teamLab Future World permanent installation.",
  },
  {
    name: "ARTE Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [
      { city: "Seoul", state: undefined, country: "South Korea" },
      { city: "Yeosu", state: undefined, country: "South Korea" },
      { city: "Gangneung", state: undefined, country: "South Korea" },
      { city: "Busan", state: undefined, country: "South Korea" },
    ],
    contacts: [],
    status: "To Contact" as const,
    category: "Ultimate Dream Goal" as const,
    notes: "Multiple immersive venues across Korea.",
  },

  // --- venues-to-add-2.md — Accessible ---
  {
    name: "Hirshhorn Museum",
    url: "https://hirshhorn.si.edu/",
    submissionFormUrl: undefined,
    locations: [{ city: "Washington", state: "DC", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Walker Art Center",
    url: "https://walkerart.org/",
    submissionFormUrl: undefined,
    locations: [{ city: "Minneapolis", state: "MN", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Contemporary Arts Center",
    url: "https://www.contemporaryartscenter.org/",
    submissionFormUrl: undefined,
    locations: [{ city: "Cincinnati", state: "OH", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "High Museum of Art",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Atlanta", state: "GA", country: "USA" }],
    contacts: [
      { name: undefined, title: undefined, email: "exhibitionproposals@high.org", notes: "Submissions accepted" },
    ],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Submissions accepted.",
  },
  {
    name: "Nerman Museum of Contemporary Art",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: undefined, state: "KS", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Lawrence Arts Center",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Lawrence", state: "KS", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Bruce Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Greenwich", state: "CT", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Holly's 2021 venue!",
  },
  {
    name: "Mad Arts Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: undefined, state: undefined, country: undefined }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Location varies. Showed Holly's work.",
  },
  {
    name: "ART06870 Gallery",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Greenwich", state: "CT", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Showed Holly's work.",
  },
  {
    name: "The Lume",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Indianapolis", state: "IN", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Dedicated immersive digital art space.",
  },
  {
    name: "Centre Pompidou",
    url: "https://www.centrepompidou.fr/en",
    submissionFormUrl: undefined,
    locations: [{ city: "Paris", state: undefined, country: "France" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Tate Modern",
    url: "https://www.tate.org.uk/visit/tate-modern",
    submissionFormUrl: undefined,
    locations: [{ city: "London", state: undefined, country: "UK" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "V&A Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "London", state: undefined, country: "UK" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Serpentine Galleries",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "London", state: undefined, country: "UK" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Strong new media program under Hans Ulrich Obrist.",
  },
  {
    name: "National Museum of Contemporary Art",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Athens", state: undefined, country: "Greece" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Focus on contemporary installations, video, photography.",
  },
  {
    name: "Stedelijk Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Amsterdam", state: undefined, country: "Netherlands" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "K Museum of Contemporary Art",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Seoul", state: undefined, country: "South Korea" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: 'Already showed Holly\'s "Let in, Let go"!',
  },
  {
    name: "Borusan Contemporary",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Istanbul", state: undefined, country: "Turkey" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "bitforms gallery",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Supports collection of ephemeral, time-based, and digital art.",
  },
  {
    name: "Danger Gallery",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Stamford", state: "CT", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Holly's own space!",
  },
  {
    name: "Asian Art Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "San Francisco", state: "CA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Art Gallery of South Australia",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Adelaide", state: undefined, country: "Australia" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Coventry Digital Art Gallery",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Coventry", state: undefined, country: "UK" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "UK's first permanent immersive digital art gallery.",
  },
  {
    name: "Videotage",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Hong Kong", state: undefined, country: "China" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Platform for video and new media art promotion.",
  },
  {
    name: "Para Site",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Hong Kong", state: undefined, country: "China" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "National Museum of Korea",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Seoul", state: undefined, country: "South Korea" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Has immersive technology galleries.",
  },
  {
    name: "Ignite Broward Art & Light Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Fort Lauderdale", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: 'Holly\'s current "Lighthouse" venue!',
  },
  {
    name: "Illuminus Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Boston", state: "MA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: 'Already showed Holly\'s "Let in, Let go".',
  },
  {
    name: "Satellite Art Show",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Miami Art Week. Already showed Holly's work.",
  },
  {
    name: "Sour Milk Art Exhibition",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Greenwich", state: "CT", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Showed Holly's 2018 work.",
  },
  {
    name: "Burning Man",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Black Rock Desert", state: "NV", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Holly has performed here as VJ.",
  },
  {
    name: "SXSW",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Austin", state: "TX", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Venice Biennale",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Venice", state: undefined, country: "Italy" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Ars Electronica Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Linz", state: undefined, country: "Austria" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },

  // --- venues-to-add-3.md — Museums & Galleries (Accessible) ---
  {
    name: "Museum of Modern Art (MoMA)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "MoMA PS1",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Queens", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Solomon R. Guggenheim Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "SFMOMA",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "San Francisco", state: "CA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "LACMA",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Los Angeles", state: "CA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "The Broad",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Los Angeles", state: "CA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Moderna Museet",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Stockholm", state: undefined, country: "Sweden" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "National Gallery of Victoria (NGV)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Melbourne", state: undefined, country: "Australia" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Mori Art Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Tokyo", state: undefined, country: "Japan" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "M+",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Hong Kong", state: undefined, country: "China" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Brooklyn Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Brooklyn", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Dia Beacon",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Beacon", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Superblue",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "AREA15",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Las Vegas", state: "NV", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "The Sphere",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Las Vegas", state: "NV", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "The Shed",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Open call pathway.",
  },
  {
    name: "The Kitchen",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Institute of Contemporary Art (ICA Boston)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Boston", state: "MA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Institute of Contemporary Art (ICA Philadelphia)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Philadelphia", state: "PA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Pérez Art Museum Miami (PAMM)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Contemporary Arts Museum Houston",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Houston", state: "TX", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Museum of Contemporary Art San Diego (MCASD)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "San Diego", state: "CA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Museum of Contemporary Art Denver (MCA Denver)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Denver", state: "CO", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "MOCA Cleveland",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Cleveland", state: "OH", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Wexner Center for the Arts",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Columbus", state: "OH", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Crystal Bridges Museum of American Art",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Bentonville", state: "AR", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "The Aldrich Contemporary Art Museum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Ridgefield", state: "CT", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Scottsdale Museum of Contemporary Art (SMoCA)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Scottsdale", state: "AZ", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "The Momentary",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Bentonville", state: "AR", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Museum of the Moving Image",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Queens", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },

  // --- venues-to-add-3.md — Science + Learning (Unconventional) ---
  {
    name: "Exploratorium",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "San Francisco", state: "CA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Science + learning venue, often strong infrastructure.",
  },
  {
    name: "Museum of Science",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Boston", state: "MA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Science + learning venue, often strong infrastructure.",
  },
  {
    name: "The Franklin Institute",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Philadelphia", state: "PA", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Science + learning venue, often strong infrastructure.",
  },
  {
    name: "Adler Planetarium",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Chicago", state: "IL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Science + learning venue, often strong infrastructure.",
  },
  {
    name: "Grace Farms",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New Canaan", state: "CT", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: undefined,
  },

  // --- venues-to-add-3.md — Hospitality / Art-Programmed (Unconventional) ---
  {
    name: "Faena Hotel Miami Beach",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami Beach", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Faena District. Hospitality venue, projection-friendly.",
  },
  {
    name: "Faena Art Project Room",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami Beach", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Commissions/hosts experimental, site-specific work.",
  },
  {
    name: "Faena Forum",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami Beach", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Major event/venue platform within the Faena district. Potential scale + production support.",
  },
  {
    name: "21c Museum Hotels",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [
      { city: "Louisville", state: "KY", country: "USA" },
      { city: "Nashville", state: "TN", country: "USA" },
      { city: "St. Louis", state: "MO", country: "USA" },
    ],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Museum hotel with multiple locations.",
  },
  {
    name: "The Cosmopolitan of Las Vegas",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Las Vegas", state: "NV", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Built-in lobby digital art platform (columns + long panel).",
  },
  {
    name: "The Standard, High Line",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "History of immersive installs/pop-ups in prominent public-facing areas.",
  },
  {
    name: "Pendry Hotels",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: undefined, state: undefined, country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: 'Known for "arrival" installations; includes a documented projection artwork example.',
  },
  {
    name: "The Miami Beach EDITION",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami Beach", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Has hosted major light-based lobby installation programming during Art Basel.",
  },
  {
    name: "SLS Brickell",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Documented interactive digital lobby installation precedent.",
  },
  {
    name: "The LINE Hotels",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [
      { city: "Austin", state: "TX", country: "USA" },
      { city: "Washington", state: "DC", country: "USA" },
      { city: "Los Angeles", state: "CA", country: "USA" },
    ],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Ongoing art activations and artist opportunities.",
  },
  {
    name: "No Vacancy",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Miami Beach", state: "FL", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Juried program placing site-specific work in iconic Miami Beach hotels.",
  },

  // --- venues-to-add-3.md — Public Realm (Unconventional) ---
  {
    name: "High Line Plinth",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Rotating major contemporary commissions.",
  },
  {
    name: "High Line Art",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "New York", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Unconventional" as const,
    notes: "Ongoing curated public art program, often very visible + press-friendly.",
  },

  // --- venues-to-add-3.md — Festivals (Accessible) ---
  {
    name: "Vivid Sydney",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Sydney", state: undefined, country: "Australia" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "May 22 - June 13, 2026.",
  },
  {
    name: "Fête des Lumières",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Lyon", state: undefined, country: "France" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Dec 5-8, 2025; held annually around Dec 8.",
  },
  {
    name: "Amsterdam Light Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Amsterdam", state: undefined, country: "Netherlands" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Nov 27, 2025 - Jan 18, 2026.",
  },
  {
    name: "Festival of Lights (Berlin)",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Berlin", state: undefined, country: "Germany" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Oct 9-18, 2026.",
  },
  {
    name: "Signal Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Prague", state: undefined, country: "Czech Republic" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Oct 15-18, 2026.",
  },
  {
    name: "Noor Riyadh",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Riyadh", state: undefined, country: "Saudi Arabia" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Nov 20 - Dec 6, 2025; recurring.",
  },
  {
    name: "Sharjah Light Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Sharjah", state: undefined, country: "UAE" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Feb 3-15, 2026.",
  },
  {
    name: "Lux Helsinki",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Helsinki", state: undefined, country: "Finland" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Jan 6-11, 2026.",
  },
  {
    name: "Copenhagen Light Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Copenhagen", state: undefined, country: "Denmark" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Jan 30 - Feb 22, 2026.",
  },
  {
    name: "GLOW Eindhoven",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Eindhoven", state: undefined, country: "Netherlands" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Nov 7-14, 2026.",
  },
  {
    name: "Llum BCN",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Barcelona", state: undefined, country: "Spain" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Feb 6-8, 2026.",
  },
  {
    name: "Light.Move.Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Łódź", state: undefined, country: "Poland" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Sept 25-27, 2026.",
  },
  {
    name: "Illuminate Adelaide",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Adelaide", state: undefined, country: "Australia" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "July 1-19, 2026.",
  },
  {
    name: "Light to Night Singapore",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Singapore", state: undefined, country: "Singapore" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Jan 9-31, 2026.",
  },
  {
    name: "i Light Singapore",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Singapore", state: undefined, country: "Singapore" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "2026 open call posted; last edition ran May 29 - Jun 21, 2025.",
  },
  {
    name: "BLINK",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [
      { city: "Cincinnati", state: "OH", country: "USA" },
      { city: undefined, state: "KY", country: "USA" },
    ],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Oct 8-11, 2026. Cincinnati + Northern Kentucky.",
  },
  {
    name: "Nuit Blanche Toronto",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Toronto", state: undefined, country: "Canada" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Oct 3, 2026; 7pm-7am.",
  },
  {
    name: "Montréal en Lumière",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Montréal", state: undefined, country: "Canada" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Feb 27 - Mar 7, 2026.",
  },
  {
    name: "Portland Winter Light Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Portland", state: "OR", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Feb 6-14, 2026.",
  },
  {
    name: "LUMA Projection Arts Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Binghamton", state: "NY", country: "USA" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "Sept 5-6, 2025.",
  },
  {
    name: "Geneva Lux",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Geneva", state: undefined, country: "Switzerland" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Rendez-vous Bundesplatz",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Bern", state: undefined, country: "Switzerland" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "LILU Light Festival Lucerne",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Lucerne", state: undefined, country: "Switzerland" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Bella Skyway Festival",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Toruń", state: undefined, country: "Poland" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: undefined,
  },
  {
    name: "Circle of Light",
    url: undefined,
    submissionFormUrl: undefined,
    locations: [{ city: "Moscow", state: undefined, country: "Russia" }],
    contacts: [],
    status: "To Contact" as const,
    category: "Accessible" as const,
    notes: "International Festival of Light.",
  },
];
